[BUGFIX] Fix docs_integration pipeline (#5734)
* Install aws-glue-libs from github repo in docusaurus_tests stage

* Add some logger.debug messages

* Use SparkContext.getOrCreate() in aws_glue_deployment_patterns.py

Causing ValueError: Cannot run multiple SparkContexts at once

See https://stackoverflow.com/a/47731444

* Use correct suite name in bigquery integration test

great_expectations.exceptions.exceptions.DataContextError: expectation_suite test_suite_2 not found

* Ignore type checking on 4 variables

* Use the name of the temp table instead of 'ge_temp' in bigquery integration test

* Use correct validator var in bigquery integration test

Also, "the truth value of a DataFrame is ambiguous" so don't just assert
the dataframe that comes back from validator.head(..)

* Add requirements-dev-azure.txt to requirements-dev.txt

* Update the 'install dependencies' step of docs_integration pipeline