Revert "Fix ModuleNotFoundError: No module named 'contrib' for capitalone"
This reverts commit ea633f9738360c9a504233fb2106a44c857c73e2.

(new error)
ModuleNotFoundError: No module named 'capitalone_dataprofiler_expectations.capitalone_dataprofiler_expectations'