Feature/refactor and type expectation diagnostic report (#3929)
* Initial scaffolding. One type and one test

* Scaffold most of the rest of the objects we'll need, with some tests.

* Add tests to unpack the behavior of @dataclass combined with SerializableDotDict

* More WIP, especially tests

* A spate of renaming and tightening

* Add SerializableDotDict.keys

* Update expectation_test_data_cases to use SerializableDictDot

* Fix gtypos

* Update SerializableDictDot, with tests

* The meat of the refactor, mostly done with some WIP

* Fixed test__count_positive_and_negative_example_cases

* Decruft

* Fix test_include_in_gallery_flag

* Make .to_dict recursive

* Linting

* Remove pydantic; Remove submessages in execution_engines; test_generate_diagnostic_checklist__first_iteration now passes

* Refactor _count_unexpected_cases_and_get_sub_messages into _count_unexpected_cases

* Fix docstring

* Clean up types and methods around LibraryMetadata

* Add support for enum serialization

* Implement LegacyAugmentedLibraryMetadataAdapter; Tidy up a little

* Small rename

* Remove pydantic

* Remove pydantic

* Remove pydantic

* Minor bugfixes. Many docstrings

* Add docstrings for test_data_cases

* Improve _get_metric_diagnostics_list

* Clean up _get_test_results

* Work on docstrings and more bug fixes. Re-up pydantic. Need to get out of the weeds soon.

* Deprecate LegacyAugmentedLibraryMetadataAdapter

* Tidy up rendering methods

* Add RendererTestDiagnostics object

* Add unit tests for _get_augmented_library_metadata

* Add unit tests for _get_augmented_library_metadata and _get_examples

* Unit test for _get_description_diagnostics

* Implement OtherExpectationTestDiagnostics

* Flow typed ExecutedExpectationTestCases through

* Remove dependence on global _registered_renderers. Get another test to pass.

* Get another test to pass

* Fix another test

* Fix another test

* Clean up tests and get business logic for Has at least one positive and negative example case, and all test cases pass working

* Decruft. Skip one failing test

* black

* isort

* Comment out pydantic

* isort and black

* Lint manually

* Lint manually

* Feature/changes from novuum jan3 review (#3941)

* Add ExpectationDiagnosticMaturityMessages class and refactor around it

* Add optional AugmentedLibraryMetadata.package and ExpectationDiagnosticCheckMessage.doc_url

* Decruft

* Linting

* Fix mismatched string in tests

* Delete test_expectation__get_execution_engine_dict

_get_execution_engine_dict was replaced by
_get_execution_engine_diagnostics

* Update tests/expectations/test_expectation_diagnostics.py

Co-authored-by: Don Heppner <donald.heppner@gmail.com>

* Implement ExpectationDiagnostics.to_json_dict method and use in build_gallery.py script

* Update build_gallery.py script to collect expectation tracebacks and display before writing gallery json file

* Allow ExpectationTestDataCases to receive 'schemas'

* Add commented-out 'test_backends' attribute to ExpectationTestDataCases class

* Add a mysql docker image that works with M1 Macs

% docker-compose up
Pulling mysql_db (mysql:8.0.20)...
8.0.20: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

* Ensure that the 'configuration' object passed to renderers are typed objects

* Update build_gallery.py script to not die if there are expectation tracebacks

* Use dot notation for args passed to ExpectationDiagnosticCheckMessage

Co-authored-by: Ken Wade <ken@superconductive.com>
Co-authored-by: Don Heppner <donald.heppner@gmail.com>